//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOperator
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string HelpLine { get; set; }
    }
}
